name: stsci
channels:
  - defaults
  - conda-forge
dependencies:
  - appdirs>=1.4.4
  - asdf>=2.12.0
  - asdf-standard>=1.0.2
  - asdf-transform-schemas>=0.2.2
  - astropy>=5.1
  - astroquery>=0.4.6
  - asttokens>=2.0.5
  - atomicwrites>=1.4.0
  - attrs>=21.4.0
  - backcall>=0.2.0
  - beautifulsoup4>=4.11.1
  - black>=19.10b0
  - blas>=1.0
  - blosc>=1.21.0
  - bottleneck>=1.3.5
  - brotli>=1.0.9
  - brotlipy>=0.7.0
  - bzip2>=1.0.8
  - ca-certificates>=2022.07.19
  - certifi>=2022.6.15
  - cffi>=1.15.0
  - cfitsio>=3.470
  - charls>=2.2.0
  - charset-normalizer>=2.0.4
  - click>=8.0.4
  - cloudpickle>=2.0.0
  - colorama>=0.4.5
  - coverage>=6.3.2
  - cryptography>=37.0.1
  - cycler>=0.11.0
  - cytoolz>=0.11.0
  - dask-core>=2022.7.0
  - debugpy>=1.5.1
  - decorator>=5.1.1
  - eigen>=3.3.7
  - entrypoints>=0.4
  - et_xmlfile>=1.1.0
  - executing>=0.8.3
  - fonttools>=4.25.0
  - freetype>=2.10.4
  - fsspec>=2022.3.0
  - giflib>=5.2.1
  - glib>=2.69.1
  - gst-plugins-base>=1.18.5
  - gstreamer>=1.18.5
  - gwcs>=0.17.1
  - hdf5>=1.12.1
  - html5lib>=1.1
  - hypothesis>=6.29.3
  - icc_rt>=2019.0.0
  - icu>=58.2
  - idna>=3.3
  - imagecodecs>=2021.8.26
  - imageio>=2.19.3
  - importlib-metadata>=4.11.3
  - importlib-resources>=5.9.0
  - importlib_metadata>=4.11.3
  - importlib_resources>=5.9.0
  - iniconfig>=1.1.1
  - intel-openmp>=2021.4.0
  - ipykernel>=6.9.1
  - ipython>=8.4.0
  - jedi>=0.18.1
  - jmespath>=0.10.0
  - joblib>=1.1.0
  - jpeg>=9e
  - jsonschema>=4.4.0
  - jupyter_client>=7.2.2
  - jupyter_core>=4.10.0
  - keyring>=23.4.0
  - kiwisolver>=1.4.2
  - lcms2>=2.12
  - lerc>=3.0
  - libaec>=1.0.4
  - libdeflate>=1.8
  - libffi>=3.4.2
  - libiconv>=1.16
  - libogg>=1.3.5
  - libpng>=1.6.37
  - libprotobuf>=3.20.1
  - libsodium>=1.0.18
  - libtiff>=4.2.0
  - libvorbis>=1.3.7
  - libwebp>=1.2.2
  - libwebp-base>=1.2.2
  - libxml2>=2.9.14
  - libxslt>=1.1.35
  - libzopfli>=1.0.3
  - locket>=1.0.0
  - lxml>=4.9.1
  - lz4-c>=1.9.3
  - matplotlib>=3.5.1
  - matplotlib-base>=3.5.1
  - matplotlib-inline>=0.1.2
  - mkl>=2021.4.0
  - mkl-service>=2.4.0
  - mkl_fft>=1.3.1
  - mkl_random>=1.2.2
  - mplcursors>=0.5.1
  - mplfinance>=0.12.9b1
  - munkres>=1.1.4
  - mypy_extensions>=0.4.3
  - natsort>=7.1.1
  - nest-asyncio>=1.5.5
  - networkx>=2.8.4
  - nltk>=3.7
  - numexpr>=2.8.3
  - numpy>=1.21.5
  - numpy-base>=1.21.5
  - opencv>=4.5.5
  - openjpeg>=2.4.0
  - openpyxl>=3.0.10
  - openssl>=1.1.1q
  - packaging>=21.3
  - pandas>=1.4.3
  - pandas-datareader>=0.10.0
  - parso>=0.8.3
  - partd>=1.2.0
  - pathspec>=0.7.0
  - patsy>=0.5.2
  - pcre>=8.45
  - photutils>=1.4.0
  - pickleshare>=0.7.5
  - pillow>=9.2.0
  - pip>=22.1.2
  - pluggy>=1.0.0
  - prompt-toolkit>=3.0.20
  - psutil>=5.9.0
  - pure_eval>=0.2.2
  - py>=1.11.0
  - pycparser>=2.21
  - pyerfa>=2.0.0
  - pygments>=2.11.2
  - pyopenssl>=22.0.0
  - pyparsing>=3.0.4
  - pyqt>=5.9.2
  - pyrsistent>=0.18.0
  - pysocks>=1.7.1
  - pytest>=7.1.2
  - pytest-arraydiff>=0.3
  - pytest-astropy>=0.10.0
  - pytest-astropy-header>=0.1.2
  - pytest-cov>=3.0.0
  - pytest-doctestplus>=0.11.1
  - pytest-filter-subpackage>=0.1.1
  - pytest-mock>=3.7.0
  - pytest-openfiles>=0.5.0
  - pytest-remotedata>=0.3.2
  - python>=3.10.4
  - python-dateutil>=2.8.2
  - python_abi>=3.10
  - pytz>=2022.1
  - pyvo>=1.3
  - pywavelets>=1.3.0
  - pywin32>=302
  - pywin32-ctypes>=0.2.0
  - pyyaml>=6.0
  - pyzmq>=23.2.0
  - qt>=5.9.7
  - regex>=2022.7.9
  - requests>=2.28.1
  - scikit-image>=0.19.2
  - scikit-learn>=1.1.1
  - scipy>=1.7.3
  - seaborn>=0.11.2
  - semantic_version>=2.8.5
  - setuptools>=61.2.0
  - sip>=4.19.13
  - six>=1.16.0
  - snappy>=1.1.9
  - sortedcontainers>=2.4.0
  - soupsieve>=2.3.1
  - sqlite>=3.38.5
  - stack_data>=0.2.0
  - statsmodels>=0.13.2
  - threadpoolctl>=2.2.0
  - tifffile>=2021.7.2
  - tk>=8.6.12
  - toml>=0.10.2
  - tomli>=2.0.1
  - toolz>=0.11.2
  - tornado>=6.1
  - tqdm>=4.64.0
  - traitlets>=5.1.1
  - typed-ast>=1.4.3
  - typing_extensions>=4.1.1
  - tzdata>=2022a
  - urllib3>=1.26.9
  - vc>=14.2
  - vs2015_runtime>=14.27.29016
  - wcwidth>=0.2.5
  - webencodings>=0.5.1
  - wheel>=0.37.1
  - win_inet_pton>=1.1.0
  - wincertstore>=0.2
  - xz>=5.2.5
  - yaml>=0.2.5
  - zeromq>=4.3.4
  - zfp>=0.5.5
  - zipp>=3.8.0
  - zlib>=1.2.12
  - zstd>=1.4.9
  - pip:
    - casjobs>=0.0.2
    - cython>=0.29.32
    - fastkde>=1.0.19
    - mastcasjobs>=0.0.5
    - multitasking>=0.0.11
